# Generated by Django 4.1.13 on 2025-05-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diseases',
            table='Diseases',
        ),
        migrations.AlterModelTable(
            name='symptom',
            table='Symptom',
        ),
    ]
