# Generated by Django 4.1.13 on 2025-05-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_diseases_table_alter_symptom_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownerappointvet',
            fields=[
                ('petid', models.OneToOneField(db_column='petID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.pet')),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('accepted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ownerappointvet',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='ownerbookpackage',
            name='petid',
        ),
        migrations.DeleteModel(
            name='Ownerdaycarechat',
        ),
        migrations.RemoveField(
            model_name='ownerratesvet',
            name='vid',
        ),
        migrations.DeleteModel(
            name='Ownervetchat',
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
        migrations.RemoveField(
            model_name='pethassymptom',
            name='petid',
        ),
        migrations.DeleteModel(
            name='Ownerbookpackage',
        ),
        migrations.DeleteModel(
            name='Ownerratesvet',
        ),
        migrations.DeleteModel(
            name='Pethassymptom',
        ),
    ]
