# Generated by Django 4.1.13 on 2025-05-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_ownerappointvet_delete_authuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownerratesvet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'ownerratesvet',
                'managed': False,
            },
        ),
    ]
